name: Get deployments

concurrency:
  group: preview-${{ github.head_ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: "Deployment name"
        required: true
env:
  NODE_VERSION: 16
  DEPLOYMENT_NAME: ${{ github.event.inputs.environment }}

jobs:
  test-job:
    env:
      BRANCH_NAME: ${{ (github.head_ref) }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Run script
        uses: actions/github-script@v6
        with:
          script: |
            const script = require('./.github/actions/getDeployments.js')
            const res = await script({ github, context, core })
